lobbies:
  - "lobby"

entries:
  - server-ip: 127.0.0.1
    server-port: 10305
    isLobbyServer: true
    transferOnShutdown: true
    password: must16keyslength
    description: Synapse Nukkit Server
