name: SynapseAPI
main: org.itxtech.synapseapi.SynapseAPI
version: "PM1E"
api: "1.0.9"
load: STARTUP
author: iTXTech, PetteriM1

commands:
  transfer:
    description: Switch server
    usage: "/transfer <target>"
    permission: synapse.transfer
  srv:
    description: Switch server
    usage: "/srv <target>"
    permission: synapse.transfer
  hub:
    description: Transfer to lobby
    usage: "/hub"
    permission: synapse.transfer.hub
  lobby:
    description: Transfer to lobby
    usage: "/lobby"
    permission: synapse.transfer.hub
permissions:
  synapse.transfer:
    description: "Allows player to transfer to other server"
    default: true
  synapse.transfer.hub:
    description: "Allows player to transfer to lobby"
    default: true
